version: '3.1'
services:

  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - './laravel-php:/application' 
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'

  php-fpm:
    build: phpdocker/php-fpm 
    working_dir: /application
    volumes:
      - './laravel-php:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini'